### ISSUE TITLE
inplace is undefined

### ISSUE THREAD

**Issue by pmcelhaney** [markis/jest-ratchet#47]
I just installed jest-ratchet and I'm getting the following error.

```
Error: An error occurred while adding the reporter at path "/code/omega/node_modules/jest-ratchet/index.js"._inplace is not defined
    at reporters.forEach (/code/omega/node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:510:15)
    at Array.forEach (<anonymous>)
    at TestScheduler._addCustomReporters (/code/omega/node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:497:15)
    at TestScheduler._setupReporters (/code/omega/node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:466:12)
    at new TestScheduler (/code/omega/node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:193:10)
    at /code/omega/node_modules/jest/node_modules/jest-cli/build/runJest.js:452:27
    at Generator.next (<anonymous>)
    at step (/code/omega/node_modules/jest/node_modules/jest-cli/build/runJest.js:107:30)
    at /code/omega/node_modules/jest/node_modules/jest-cli/build/runJest.js:118:15
```

The source is this line in index.js.

```js
var inplace = _inplace;
```

It seems to come down to the fact that `json-in-place` is external in the Rollup config. The change happened in this 19c6c9547ff3dac0b3793074698ffe239c964d8f. 

I can fix it by manually editing the index.js. There's another line further down where I had to do the same thing for yargs_parser. 

```js
var inplace = require('json-in-place');
```

This works, but manually editing a file in node_modules isn't a solution. I could send a PR with the updated .js file, but it's just going to get broken again the next time a build is run. I'm guessing something needs to be changed in the Rollup or TypeScript config. 

In the meantime, this library seems to be working for others. Maybe I'm just doing something wrong?

**Comment by markis** [comment]
jest-ratchet@1.3.2 has been published
